apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
      - name: dotnet-api
        image: acrregistry932409.azurecr.io/webappdocker:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-api-service
spec:
  type: LoadBalancer
  selector:
    app: dotnet-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080